### ISSUE TITLE
Controller Daemon issue

### ISSUE THREAD

**Issue by bmyoh** [lowasis/apollo_record#13] opened 2018-11-16 08:41 UTC
Hi,
Few days ago, I wrote the daemon script and made a pull request. 
But I found an important problem. Sometimes the controller process does not run at startup. 
In my opinion, It couldn't create IPC socket.

Please check it out and let me know.

**Comment by lowasis** [comment] 2018-11-16 13:22
It seems that problem is caused by this scenario.

1. monitor process is started.
2. but monitor process is not yet initialized unix socket.
3. controller process is strted.
4. controller process is trying to connect unix socket.

I think that the solution is insert "sleep few sec" before run controller in daemon script.
This script's contributor is you, so could you fix this issue?

**Comment by bmyoh** [comment] 2018-11-19 00:55
Sure!
I'l l fix it. :)

**Comment by lowasis** [comment] 2018-11-22 05:00
I merged your source.
Thank you for your supporting

**Closed as completed by lowasis** 2018-11-22 05:00 UTC
